// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyjxkogzsqiekbawwhgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5anhrb2d6c3FpZWtiYXd3aGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTM1NTgsImV4cCI6MjA2ODM4OTU1OH0.8hJxRD86Lhc-4PAOXjXVWWCLHGWqY3Mu9U6lHo0IxPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with session token header injection
const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Proxy to inject session token header automatically
export const supabase = new Proxy(supabaseClient, {
  get(target, prop) {
    const originalMethod = target[prop as keyof typeof target];
    
    if (prop === 'from' && typeof originalMethod === 'function') {
      return function(tableName: string) {
        const sessionToken = localStorage.getItem('secure_session');
        const tableQuery = originalMethod.call(target, tableName);
        
        if (sessionToken) {
          // Inject session token header for RLS validation
          const decodedToken = atob(sessionToken);
          return new Proxy(tableQuery, {
            get(queryTarget, queryProp) {
              const queryMethod = queryTarget[queryProp as keyof typeof queryTarget];
              if (typeof queryMethod === 'function') {
                return function(...args: any[]) {
                  const result = queryMethod.apply(queryTarget, args);
                  if (result && typeof result === 'object' && 'headers' in result) {
                    result.headers = { ...result.headers, 'x-session-token': decodedToken };
                  }
                  return result;
                };
              }
              return queryMethod;
            }
          });
        }
        return tableQuery;
      };
    }
    
    return originalMethod;
  }
});